basePath: /api
definitions:
  ota.Activation:
    properties:
      challenge:
        description: 用于设备认证挑战
        type: string
      code:
        example: "543091"
        type: string
      message:
        example: Anime AI Chat 543091
        type: string
    type: object
  ota.FirmwareInfo:
    properties:
      url:
        example: /ota_bin/1.2.4.bin
        type: string
      version:
        example: 1.2.4
        type: string
    type: object
  ota.MQTTInfo:
    properties:
      client_id:
        example: CGID_test@@@mac@@@client
        type: string
      endpoint:
        example: mqtt://broker:1883
        type: string
      password:
        example: randomPwd
        type: string
      publish_topic:
        example: device-server
        type: string
      subscribe_topic:
        example: "null"
        type: string
      username:
        example: base64string
        type: string
    type: object
  ota.OTAResponse:
    properties:
      activation:
        $ref: '#/definitions/ota.Activation'
      firmware:
        $ref: '#/definitions/ota.FirmwareInfo'
      mqtt:
        $ref: '#/definitions/ota.MQTTInfo'
      server_time:
        $ref: '#/definitions/ota.ServerTimeInfo'
      websocket:
        $ref: '#/definitions/ota.WebSocketInfo'
    type: object
  ota.ServerTimeInfo:
    properties:
      timestamp:
        example: 1720065289451
        type: integer
      timezone_offset:
        example: 480
        type: integer
    type: object
  ota.WebSocketInfo:
    properties:
      url:
        example: wss://your-server/ws
        type: string
    type: object
  vision.VisionAnalysisData:
    properties:
      error:
        description: 错误信息（失败时）
        type: string
      result:
        description: 分析结果（成功时）
        type: string
    type: object
  webapi.SystemConfig:
    properties:
      prompt:
        type: string
      selectedASR:
        type: string
      selectedLLM:
        type: string
      selectedTTS:
        type: string
      selectedVLLLM:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: 小智服务端，包含OTA与Vision等接口
  title: 小智服务端 API 文档
  version: "1.0"
paths:
  /admin/system:
    get:
      description: 获取服务器的系统配置信息，包括选择的提供商和默认提示词
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/webapi.SystemConfig'
        "401":
          description: Unauthorized
          schema:
            type: object
      security:
      - BearerAuth: []
      summary: 获取系统配置
      tags:
      - Admin
  /cfg:
    get:
      description: 检查配置服务的运行状态
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: 检查配置服务状态
      tags:
      - Config
  /ota/:
    post:
      consumes:
      - application/json
      description: 处理设备OTA请求，包括设备注册、激活码生成和固件信息返回
      parameters:
      - description: 设备ID
        in: header
        name: device-id
        required: true
        type: string
      - description: 客户端ID
        in: header
        name: client-id
        required: true
        type: string
      - description: 设备信息
        in: body
        name: body
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ota.OTAResponse'
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: OTA设备注册和固件更新
      tags:
      - OTA
  /vision:
    get:
      description: 获取Vision服务的运行状态和可用模型信息
      produces:
      - text/plain
      responses:
        "200":
          description: 服务状态信息
          schema:
            type: string
      summary: 检查Vision服务状态
      tags:
      - Vision
    post:
      consumes:
      - multipart/form-data
      description: 上传图片并进行视觉分析，支持问题询问
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 设备ID
        in: header
        name: Device-Id
        required: true
        type: string
      - description: 客户端ID
        in: header
        name: Client-Id
        required: true
        type: string
      - description: 图片文件
        in: formData
        name: file
        required: true
        type: file
      - description: 分析问题
        in: formData
        name: question
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vision.VisionAnalysisData'
        "400":
          description: Bad Request
          schema:
            type: object
        "401":
          description: Unauthorized
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: 图片视觉分析
      tags:
      - Vision
swagger: "2.0"
