name: Build Go binaries

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  workflow_dispatch:

env:
  OPUS_VERSION: 1.3.1

permissions:
  contents: write

jobs:
  build-windows-amd64:
    runs-on: ubuntu-latest
    outputs:
      binary: windows-amd64-server.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Install cross-compilation tools
        run: |
          sudo apt update
          sudo apt install -y mingw-w64 pkg-config build-essential wget

      - name: Download & build libopus (static)
        run: |
          wget https://archive.mozilla.org/pub/opus/opus-${OPUS_VERSION}.tar.gz
          tar xf opus-${OPUS_VERSION}.tar.gz
          pushd opus-${OPUS_VERSION}
          ./configure \
            --host=x86_64-w64-mingw32 \
            --disable-shared --enable-static \
            --disable-doc --disable-extra-programs \
            --prefix="$HOME/opus-win"
          make -j"$(nproc)"
          make install
          popd

      - name: Configure env for Windows build
        run: |
          echo "PKG_CONFIG_PATH=$HOME/opus-win/lib/pkgconfig" >> $GITHUB_ENV
          echo "CGO_ENABLED=1"                   >> $GITHUB_ENV
          echo "GOOS=windows"                   >> $GITHUB_ENV
          echo "GOARCH=amd64"                   >> $GITHUB_ENV
          echo "CC=x86_64-w64-mingw32-gcc"      >> $GITHUB_ENV

      - name: Build Windows binary
        run: |
          go mod tidy
          cd src
          go build -v \
            -ldflags "-s -w -extldflags '-static'" \
            -o ../windows-amd64-server.exe

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-amd64-server.exe
          path: windows-amd64-server.exe

  build-linux:
    strategy:
      matrix:
        include:
          - arch: amd64
            runs-on: ubuntu-latest
          - arch: arm64
            runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Compile in container
        run: |
          docker run --rm --platform=linux/${{ matrix.arch }} \
            -v "${{ github.workspace }}:/src" \
            -w /src \
            golang:1.24.2-alpine sh -c "\
              apk add --no-cache build-base autoconf automake libtool pkgconfig musl-dev wget && \
              wget https://archive.mozilla.org/pub/opus/opus-${OPUS_VERSION}.tar.gz && \
              tar xf opus-${OPUS_VERSION}.tar.gz && \
              cd opus-${OPUS_VERSION} && \
              ./configure --enable-static --disable-shared --disable-doc --disable-extra-programs && \
              make -j$(nproc) && make install && \
              cd /src && go mod tidy && cd src && \
              CGO_ENABLED=1 GOOS=linux GOARCH=${{ matrix.arch }} \
                go build -v -ldflags \"-s -w -extldflags '-static'\" \
                -o ../linux-${{ matrix.arch }}-server\
            "

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}-server
          path: linux-${{ matrix.arch }}-server

  release:
    needs:
      - build-windows-amd64
      - build-linux
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            artifacts/**/windows-amd64-server.exe
            artifacts/**/linux-amd64-server
            artifacts/**/linux-arm64-server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
